### ISSUE TITLE
Panic

### ISSUE THREAD

**Issue by AndreyBaranyuk** [uptrace/uptrace#131]
Hello, I had met panic in uptrace of previous version. 

uptrace_1       | panic: runtime error: invalid memory address or nil pointer dereference
uptrace_1       | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x798b29]
uptrace_1       | 
uptrace_1       | goroutine 7585116 [running]:
uptrace_1       | database/sql.(*Rows).close.func1()
uptrace_1       | 	database/sql/sql.go:3321 +0x29
uptrace_1       | database/sql.withLock({0x21a5f00, 0xc000216c60}, 0xc001944f00)
uptrace_1       | 	database/sql/sql.go:3439 +0x8c
uptrace_1       | database/sql.(*Rows).close(0xc002cfee00, {0x21a0ac0, 0xc00007e0c0})
uptrace_1       | 	database/sql/sql.go:3320 +0x16d
uptrace_1       | database/sql.(*Rows).awaitDone(0xc0000ae9c0?, {0x21ab718, 0xc004011380}, {0x0?, 0x0?})
uptrace_1       | 	database/sql/sql.go:2974 +0xd2
uptrace_1       | created by database/sql.(*Rows).initContextClose
uptrace_1       | 	database/sql/sql.go:2958 +0x158

**Comment by vmihailenco** [comment]
@AndreyBaranyuk do you have a full trace?

**Comment by AndreyBaranyuk** [comment]
> @AndreyBaranyuk do you have a full stacktrace?

No, sorry, I don’t have a full trace, because server made panic every time I had restarted it and it is full logs of this panic. So, after update, my issue is not actual. 

Vladimir, thank you for this service. It’s very useful for us.
