### ISSUE TITLE
Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by vasicvuk** [uptrace/uptrace#150]
On version 1.3.0 we get random crashes with **panic: runtime error: invalid memory address or nil pointer dereference**. Installed with helm chart on Kubernetes

```
2023-01-23T12:20:30.221Z error alerting/manager.go:112 eval-rule failed {"error": "Post \"http://localhost:9093/api/v2/alerts\": dial tcp [::1]:9093: connect: connection refused", "rule.name": "Always firing (for fun and testing)", "rule.query": "$goroutines >= 0 group by host.name"}
github.com/uptrace/uptrace/pkg/metrics/alerting.(*Manager).tick
github.com/uptrace/uptrace/pkg/metrics/alerting/manager.go:112
github.com/uptrace/uptrace/pkg/metrics/alerting.(*Manager).Run
github.com/uptrace/uptrace/pkg/metrics/alerting/manager.go:93
main.startAlerting.func1
github.com/uptrace/uptrace/cmd/uptrace/main.go:362
github.com/uptrace/uptrace/pkg/run.(*Group).Run.func1
github.com/uptrace/uptrace/pkg/run/group.go:40
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x106036b]
goroutine 416 [running]:
github.com/uptrace/uptrace/pkg/tracing.(*LogsServiceServer).process(0xc0004ac8d0, {0x27dbce0, 0xc001e93bf0}, 0xc000228e58, {0xc0000134e8, 0x1, 0x38?})
github.com/uptrace/uptrace/pkg/tracing/otlp_logs.go:83 +0x10b
github.com/uptrace/uptrace/pkg/tracing.(*LogsServiceServer).Export(0xc0004ac8d0, {0x27dbce0, 0xc001e93bf0}, 0xc001e91a00)
github.com/uptrace/uptrace/pkg/tracing/otlp_logs.go:70 +0x2e5
go.opentelemetry.io/proto/otlp/collector/logs/v1._LogsService_Export_Handler.func1({0x27dbce0, 0xc001e93bf0}, {0x123a8a0?, 0xc001e91a00})
go.opentelemetry.io/proto/otlp@v0.19.0/collector/logs/v1/logs_service_grpc.pb.go:90 +0x78
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1({0x27dbce0, 0xc001e93170}, {0x123a8a0, 0xc001e91a00}, 0xc001e74de0, 0xc001ea0480)
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.36.4/interceptor.go:341 +0x437
go.opentelemetry.io/proto/otlp/collector/logs/v1._LogsService_Export_Handler({0x12eb6a0?, 0xc0004ac8d0}, {0x27dbce0, 0xc001e93170}, 0xc0001c5490, 0xc0007069a0)
go.opentelemetry.io/proto/otlp@v0.19.0/collector/logs/v1/logs_service_grpc.pb.go:92 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000d65a0, {0x27e0d98, 0xc001d921a0}, 0xc000efad80, 0xc0001e7aa0, 0x3072170, 0x0)
google.golang.org/grpc@v1.51.0/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0000d65a0, {0x27e0d98, 0xc001d921a0}, 0xc000efad80, 0x0)
google.golang.org/grpc@v1.51.0/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
google.golang.org/grpc@v1.51.0/server.go:963 +0x28a
```

**Comment by vmihailenco** [comment]
Thanks for reporting. This will be fixed in v0.3.1
