### ISSUE TITLE
panic: reflect.AppendSlice: map[bfloat16.T]uint64 != bfloat16.Map

### ISSUE THREAD

**Issue by toby1991** [uptrace/uptrace#216]
```
+ '[' 0 -eq 0 ]
+ /uptrace '--config=/etc/uptrace/uptrace.yml' pg wait
2023-05-10T03:13:53.207Z	info	command/pg.go:41	PostgreSQL is up and runnining
+ /uptrace '--config=/etc/uptrace/uptrace.yml' ch wait
2023-05-10T03:13:53.227Z	info	command/ch.go:42	ClickHouse is up and runnining
+ exec /uptrace '--config=/etc/uptrace/uptrace.yml' serve
2023-05-10T03:13:53.259Z	info	uptrace/main.go:114	starting Uptrace...	{"version": "v1.4.2", "config": "/etc/uptrace/uptrace.yml"}
read the docs at            https://uptrace.dev/get/
changelog                   https://github.com/uptrace/uptrace/blob/master/CHANGELOG.md
Telegram chat               https://t.me/uptrace

OTLP/gRPC (listen.grpc)     http://project2_secret_token@localhost:14317/2
OTLP/HTTP (listen.http)     http://project2_secret_token@localhost:14318/2

Open UI (site.addr)         http://localhost:14318/

2023-05-10T03:13:53.349Z	info	tracing/span_processor.go:43	starting processing spans...	{"threads": 4, "batch_size": 4000, "buffer_size": 16000}
2023-05-10T03:13:53.362Z	info	metrics/measure_processor.go:65	starting processing metrics...	{"threads": 4, "batch_size": 4000, "buffer_size": 16000, "cum_to_delta_size": 40000}
panic: reflect.AppendSlice: map[bfloat16.T]uint64 != bfloat16.Map

goroutine 114 [running]:
github.com/uptrace/uptrace/pkg/httputil.PanicHandler.ServeHTTP.func1()
	github.com/uptrace/uptrace/pkg/httputil/middleware.go:24 +0x65
panic({0x10c2e00, 0xc000d62300})
	runtime/panic.go:884 +0x213
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.func1()
	go.opentelemetry.io/otel/sdk@v1.14.0/trace/span.go:383 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc000e9c180, {0x0, 0x0, 0xc000cee000?})
	go.opentelemetry.io/otel/sdk@v1.14.0/trace/span.go:421 +0xa89
panic({0x10c2e00, 0xc000d62300})
	runtime/panic.go:884 +0x213
reflect.typesMustMatch({0x12c9a76, 0x13}, {0x2921ad8?, 0x111a960}, {0x2921ad8?, 0x113d240})
	reflect/value.go:2768 +0x105
reflect.AppendSlice({0x10ac380?, 0xc000de8138?, 0x1159720?}, {0x10a7f80?, 0xc000e06348?, 0xc000fbc4c0?})
	reflect/value.go:2847 +0x115
github.com/uptrace/go-clickhouse/ch.(*scanModel).ScanBlock(0xc000f82060, 0x290e780?)
	github.com/uptrace/go-clickhouse@v0.3.2-0.20230329131310-2d63e3b0ac7b/ch/model_scan.go:44 +0x378
github.com/uptrace/go-clickhouse/ch.(*baseQuery).query(0x0?, {0x290e780, 0xc000fb8330}, {0x29034e0?, 0xc000f82060?}, {0xc0005e1000?, 0x290eda0?})
	github.com/uptrace/go-clickhouse@v0.3.2-0.20230329131310-2d63e3b0ac7b/ch/query_base.go:121 +0x151
github.com/uptrace/go-clickhouse/ch.(*SelectQuery).scan(0xc00044b180, {0x290e780, 0xc000fb8120}, 0x1, {0xc000fee3c8?, 0x0?, 0xc000d45080?})
	github.com/uptrace/go-clickhouse@v0.3.2-0.20230329131310-2d63e3b0ac7b/ch/query_select.go:526 +0x1b0
github.com/uptrace/go-clickhouse/ch.(*SelectQuery).ScanColumns(...)
	github.com/uptrace/go-clickhouse@v0.3.2-0.20230329131310-2d63e3b0ac7b/ch/query_select.go:502
github.com/uptrace/uptrace/pkg/metrics.(*QueryHandler).selectMetricHeatmap(0xc000558660, {0x290e780, 0xc000fb8120}, 0xc000f8e000)
	github.com/uptrace/uptrace/pkg/metrics/query_handler.go:467 +0xe18
github.com/uptrace/uptrace/pkg/metrics.(*QueryHandler).Heatmap(0x100?, {0x290e2e0, 0xc00008c1e0}, {0xc000560300, {{0xc000f9e004, 0x19}, 0xc000673c80, 0xc000430a30, 0x0}})
	github.com/uptrace/uptrace/pkg/metrics/query_handler.go:414 +0x107
github.com/uptrace/uptrace/pkg/org.(*Middleware).UserAndProject.func1({0x290e2e0, 0xc00008c1e0}, {0xc000d8a200, {{0xc000f9e004, 0x19}, 0xc000673c80, 0xc000430a30, 0x0}})
	github.com/uptrace/uptrace/pkg/org/auth.go:99 +0x324
github.com/uptrace/bunrouter/extra/bunrouterotel.(*config).Middleware.func1({0x290e2e0, 0xc00008c1e0}, {0xc000d8a200, {{0xc000f9e004, 0x19}, 0xc000673c80, 0xc000430a30, 0x0}})
	github.com/uptrace/bunrouter/extra/bunrouterotel@v1.0.20/bunrouterotel.go:70 +0xb36
github.com/uptrace/uptrace/pkg/bunapp.(*App).httpErrorHandler.func1({0x290e2e0, 0xc00008c1e0}, {0xc000d8a200, {{0xc000f9e004, 0x19}, 0xc000673c80, 0xc000430a30, 0x0}})
	github.com/uptrace/uptrace/pkg/bunapp/app.go:273 +0x88
github.com/uptrace/bunrouter/extra/reqlog.(*middleware).Middleware.func1({0x290d8c0?, 0xc000cee000?}, {0xc000d8a200, {{0xc000f9e004, 0x19}, 0xc000673c80, 0xc000430a30, 0x0}})
	github.com/uptrace/bunrouter/extra/reqlog@v1.0.20/middleware.go:78 +0x123
github.com/uptrace/bunrouter.(*Router).ServeHTTPError(0x1142ac0?, {0x290d8c0, 0xc000cee000}, 0xc000d8a200)
	github.com/uptrace/bunrouter@v1.0.20/router.go:52 +0x128
github.com/uptrace/bunrouter.(*Router).ServeHTTP(0x3131480?, {0x290d8c0?, 0xc000cee000?}, 0x4?)
	github.com/uptrace/bunrouter@v1.0.20/router.go:45 +0x25
github.com/klauspost/compress/gzhttp.NewWrapper.func1.1({0x290e310, 0xc000d30060}, 0x0?)
	github.com/klauspost/compress@v1.16.5/gzhttp/compress.go:478 +0x35a
net/http.HandlerFunc.ServeHTTP(0xc000d8a200?, {0x290e310?, 0xc000d30060?}, 0xc000df00f0?)
	net/http/server.go:2122 +0x2f
github.com/uptrace/uptrace/pkg/httputil.DecompressHandler.ServeHTTP({{0x2907600?, 0xc00102d5c0?}}, {0x290e310, 0xc000d30060}, 0xc000d8a200)
	github.com/uptrace/uptrace/pkg/httputil/middleware.go:52 +0x1b6
github.com/uptrace/uptrace/pkg/httputil.(*TraceparentHandler).ServeHTTP(0xc00102d5e0, {0x290e310, 0xc000d30060}, 0xc000d8a200)
	github.com/uptrace/uptrace/pkg/httputil/middleware.go:89 +0xb9
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP(0xc000e79bc0, {0x290d5c0?, 0xc00017e460}, 0xc000560100)
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.40.0/handler.go:213 +0x1231
github.com/rs/cors.(*Cors).Handler.func1({0x290d5c0, 0xc00017e460}, 0xc000560100)
	github.com/rs/cors@v1.9.0/cors.go:236 +0x1c4
net/http.HandlerFunc.ServeHTTP(0x82?, {0x290d5c0?, 0xc00017e460?}, 0x0?)
	net/http/server.go:2122 +0x2f
github.com/uptrace/uptrace/pkg/httputil.PanicHandler.ServeHTTP({{0x2907600?, 0xc00102d6a0?}}, {0x290d5c0?, 0xc00017e460?}, 0x116dcc0?)
	github.com/uptrace/uptrace/pkg/httputil/middleware.go:30 +0x5c
net/http.serverHandler.ServeHTTP({0xc000fb8090?}, {0x290d5c0, 0xc00017e460}, 0xc000560100)
	net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc000fd01b0, {0x290e780, 0xc000fb8570})
	net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
	net/http/server.go:3089 +0x5ed
```

**Comment by vmihailenco** [comment]
@toby1991 please upgrade to v1.4.5. This is already fixed there.
