### ISSUE TITLE
Bug: Cannot unmarshal JSON timestamp From Sentry 

### ISSUE THREAD

**Issue by invaderb** [uptrace/uptrace#245]
Hey there was testing out the browser implementation with sentry for our Angular app and keep coming across this error

```
{
    "status": 400,
    "code": "json_unmarshal",
    "message": "json: cannot unmarshal \"1688663660.5427997,\\\"timestamp\\\":1...\" into Go struct field tracing.SentryEvent[]tracing.SentrySpantracing.SentrySpan.spans.0.start_timestamp of type time.Time"
}
```

Any thoughts?

**Comment by invaderb** [comment]
ok so after some digging yesterday its not in the custom SentryTime UnmarshalJSON but in the SentrySpan struct that StartTime and EndTime are both time.Time RFC2229 format but the sentry library is sending the timestamp in unix.

I tried changing the time.Time to SentryTime in the SentrySpan struct so it get's converted but then in the processTransaction method there's a type issue with the new(Span) and that struct has time and duration which are typed as time.Time so not sure how to quite fix it...

**Comment by invaderb** [comment]
well I found a way around it by converting to ISO before sending the transaction

```
	init({
		dsn: 'http://project2_secret_token@localhost:14318/2',
		integrations: [
			new BrowserTracing({
			  tracingOrigins: [],
			  routingInstrumentation: instrumentAngularRouting,
			}),
		  ],
		tracesSampleRate: 1,
		enableTracing: true,
		environment: environment.environment,
		beforeSendTransaction: (transaction) => {
			// convert timestamps to RFC3339 format
			transaction.start_timestamp = new Date(transaction.start_timestamp! * 1000).toISOString() as any;
			transaction.timestamp = new Date(transaction.timestamp! * 1000).toISOString() as any;
			// loop through breadcrumbs and convert timestamps to RFC3339 format
			transaction.breadcrumbs?.forEach((crumb) => {
				crumb.timestamp = new Date(crumb.timestamp! * 1000).toISOString() as any;
			});
			
			// loop through spans and convert timestamps to RFC3339 format
			transaction.spans?.forEach((span) => {
				span.startTimestamp = new Date(span.startTimestamp! * 1000).toISOString() as any;
				span.endTimestamp = new Date(span.endTimestamp! * 1000).toISOString() as any;
				// convert status string to int this may or may not be correct
				if (span.status === 'ok') {
					span.status = 1 as any;
				} else {
					span.status = 0 as any;
				}
			});
			console.log(transaction);
			return transaction;
		},
	});
```
I'm now seeing a panic after getting the transactions and the application keeps closing could be because I'm on go 1.20 I'll try and switch over to 1.18 and see if that fixes the issue

```
panic: assignment to entry in nil map [recovered]
        panic: assignment to entry in nil map

goroutine 69 [running]:
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.func1()
        /go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.16.0/trace/span.go:383 +0x2c
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0x140005bdc80, {0x0, 0x0, 0x17?})
        /go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.16.0/trace/span.go:421 +0x87c
panic({0x103062280, 0x10320b3a0})
        /opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/panic.go:884 +0x204
github.com/uptrace/uptrace/pkg/tracing.initEventFromHostSpan(0x1400052db80, 0x1400052da40?, 0x1400020c8c0)
        /uptrace-dev/pkg/tracing/span_attrs.go:558 +0x1f4
github.com/uptrace/uptrace/pkg/tracing.(*SpanProcessor)._processSpans(0x140003e2660, 0x14000611e80?, {0x14000b12900, 0x5a, 0x5a?})
        /uptrace-dev/pkg/tracing/span_processor.go:180 +0xf54
github.com/uptrace/uptrace/pkg/tracing.(*SpanProcessor).processSpans.func1()
        /uptrace-dev/pkg/tracing/span_processor.go:144 +0x1d8
created by github.com/uptrace/uptrace/pkg/tracing.(*SpanProcessor).processSpans
        /uptrace-dev/pkg/tracing/span_processor.go:138 +0x178
exit status 2
```

**Comment by vmihailenco** [comment]
This should be fixed by https://github.com/uptrace/uptrace/commit/7811ea52a117ba9f9701dad2b8b5e406ae9de09f
