### ISSUE TITLE
span_processor forceSpanName interface conversion panic after upgrade to 1.7.2

### ISSUE THREAD

**Issue by singler** [uptrace/uptrace#363]
```
panic: interface conversion: interface {} is nil, not string [recovered]
	panic: interface conversion: interface {} is nil, not string

goroutine 2306 [running]:
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.deferwrap1()
	go.opentelemetry.io/otel/sdk@v1.23.1/trace/span.go:405 +0x25
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc0255aed80, {0x0, 0x0, 0xc0447dc380?})
	go.opentelemetry.io/otel/sdk@v1.23.1/trace/span.go:443 +0xa82
panic({0x17db860?, 0xc015adced0?})
	runtime/panic.go:770 +0x132
github.com/uptrace/uptrace/pkg/tracing.(*spanProcessorThread).forceSpanName(0x1989aa0?, {0x3610a20?, 0xc01137a6f0?}, 0xc00c38d008)
	github.com/uptrace/uptrace/pkg/tracing/span_processor.go:310 +0x137
github.com/uptrace/uptrace/pkg/tracing.(*spanProcessorThread).initSpanOrEvent(0xc00b8d1f68, {0x3610a20, 0xc01137a6f0}, 0xc00c38d008)
	github.com/uptrace/uptrace/pkg/tracing/span_attrs.go:47 +0x1b9
github.com/uptrace/uptrace/pkg/tracing.(*spanProcessorThread)._processSpans(0xc00b8d1f68, {0x3610a20, 0xc01137a6f0}, {0xc019076000, 0x275a, 0x275a?})
	github.com/uptrace/uptrace/pkg/tracing/span_processor.go:164 +0x1bf
github.com/uptrace/uptrace/pkg/tracing.(*SpanProcessor).processSpans.func1()
	github.com/uptrace/uptrace/pkg/tracing/span_processor.go:153 +0x1db
created by github.com/uptrace/uptrace/pkg/tracing.(*SpanProcessor).processSpans in goroutine 152
	github.com/uptrace/uptrace/pkg/tracing/span_processor.go:147 +0x165
```

**Comment by vmihailenco** [comment]
Thanks for reporting. This should be fixed in v1.7.3
