### ISSUE TITLE
Panic for query like "count() | group by _group_id" (in logs)

### ISSUE THREAD

**Issue by azat** [uptrace/uptrace#367]
```
panic: runtime error: invalid memory address or nil pointer dereference

goroutine 517 [running]:
github.com/uptrace/uptrace/pkg/httputil.PanicHandler.ServeHTTP.func1()
       github.com/uptrace/uptrace/pkg/httputil/middleware.go:25 +0x5b
panic({0x17c8a60?, 0x42dc900?})
       runtime/panic.go:770 +0x132
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.deferwrap1()
       go.opentelemetry.io/otel/sdk@v1.23.1/trace/span.go:405 +0x25
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc016149200, {0x0, 0x0, 0xc01615a140?})
       go.opentelemetry.io/otel/sdk@v1.23.1/trace/span.go:443 +0xa82
panic({0x17c8a60?, 0x42dc900?})
       runtime/panic.go:770 +0x132
github.com/uptrace/uptrace/pkg/tracing/tql.(*FuncCall).AppendString(0xc0168ae3e0, {0x0?, 0x0?, 0x9?})
       github.com/uptrace/uptrace/pkg/tracing/tql/ast.go:145 +0xd7
github.com/uptrace/uptrace/pkg/tracing/tql.String(...)
       github.com/uptrace/uptrace/pkg/tracing/tql/ast.go:26
github.com/uptrace/uptrace/pkg/tracing.compileUQL(0xc01688ac40, {0xc01689a1c0, 0x2, 0x0?}, 0x34630b8a000)
       github.com/uptrace/uptrace/pkg/tracing/span_filter.go:188 +0x8a8
github.com/uptrace/uptrace/pkg/tracing.BuildSpanIndexQuery(0xc000040aa0, 0xc0168d2000, 0x34630b8a000)
       github.com/uptrace/uptrace/pkg/tracing/span_filter.go:140 +0xb6
github.com/uptrace/uptrace/pkg/tracing.(*SpanHandler).ListGroups(0xc000d400a8, {0x360d250, 0xc01610cb90}, {0xc0168c6120, {{0xc016a70244, 0x1d}, 0xc000d35200, 0xc000745130, 0x0}})
       github.com/uptrace/uptrace/pkg/tracing/span_handler.go:117 +0x145
github.com/uptrace/uptrace/pkg/org.(*Middleware).UserAndProject-fm.(*Middleware).UserAndProject.func1({0x360d250, 0xc01610cb90}, {0xc016a74360, {{0xc016a70244, 0x1d}, 0xc000d35200, 0xc000745130, 0x0}})
       github.com/uptrace/uptrace/pkg/org/auth.go:105 +0x24f
github.com/uptrace/bunrouter/extra/bunrouterotel.(*config).Middleware-fm.(*config).Middleware.func1({0x360d250, 0xc01610cb90}, {0xc016a74360, {{0xc016a70244, 0x1d}, 0xc000d35200, 0xc000745130, 0x0}})
       github.com/uptrace/bunrouter/extra/bunrouterotel@v1.0.21/bunrouterotel.go:70 +0xa99
github.com/uptrace/uptrace/pkg/bunapp.(*App).httpErrorHandler-fm.(*App).httpErrorHandler.func1({0x360d250, 0xc01610cb90}, {0xc016a74360, {{0xc016a70244, 0x1d}, 0xc000d35200, 0xc000745130, 0x0}})
       github.com/uptrace/uptrace/pkg/bunapp/app.go:231 +0x90
github.com/uptrace/bunrouter/extra/reqlog.(*middleware).Middleware-fm.(*middleware).Middleware.func1({0x3609fa0?, 0xc01615a140?}, {0xc016a74360, {{0xc016a70244, 0x1d}, 0xc000d35200, 0xc000745130, 0x0}})
       github.com/uptrace/bunrouter/extra/reqlog@v1.0.21/middleware.go:77 +0x124
github.com/uptrace/bunrouter.(*Router).ServeHTTPError(0x793201?, {0x3609fa0, 0xc01615a140}, 0xc016a74360)
       github.com/uptrace/bunrouter@v1.0.21/router.go:52 +0x108
github.com/uptrace/bunrouter.(*Router).ServeHTTP(0x42e1f60?, {0x3609fa0?, 0xc01615a140?}, 0x4?)
       github.com/uptrace/bunrouter@v1.0.21/router.go:45 +0x1d
github.com/klauspost/compress/gzhttp.NewWrapper.func1.1({0x360d2b0, 0xc016100a20}, 0xc016a74360)
       github.com/klauspost/compress@v1.17.6/gzhttp/compress.go:495 +0x54f
net/http.HandlerFunc.ServeHTTP(0xc016a74360?, {0x360d2b0?, 0xc016100a20?}, 0x3610a20?)
       net/http/server.go:2166 +0x29
github.com/uptrace/uptrace/pkg/httputil.DecompressHandler.ServeHTTP({{0x35fcee0?, 0xc01531b800?}}, {0x360d2b0, 0xc016100a20}, 0xc016a74360)
       github.com/uptrace/uptrace/pkg/httputil/middleware.go:53 +0x1a3
github.com/uptrace/uptrace/pkg/httputil.(*TraceparentHandler).ServeHTTP(0xc01531b820, {0x360d2b0, 0xc016100a20}, 0xc016a74360)
       github.com/uptrace/uptrace/pkg/httputil/middleware.go:90 +0xb4
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP(0xc0153344e0, {0x3609eb0, 0xc016138540}, 0xc0168c6000, {0x35fcf20, 0xc01531b820})
       go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.48.0/handler.go:225 +0x1243
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1({0x3609eb0?, 0xc016138540?}, 0x529eef?)
       go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.48.0/handler.go:83 +0x35
net/http.HandlerFunc.ServeHTTP(0xc015b10540?, {0x3609eb0?, 0xc016138540?}, 0xc0168c6000?)
       net/http/server.go:2166 +0x29
main.init.func2.(*Cors).Handler.11({0x3609eb0, 0xc016138540}, 0xc0168c6000)
       github.com/rs/cors@v1.10.1/cors.go:281 +0x184
net/http.HandlerFunc.ServeHTTP(0xc016114c60?, {0x3609eb0?, 0xc016138540?}, 0x44a58b?)
       net/http/server.go:2166 +0x29
github.com/uptrace/uptrace/pkg/httputil.PanicHandler.ServeHTTP({{0x35fcee0?, 0xc01531b960?}}, {0x3609eb0?, 0xc016138540?}, 0x4a614f?)
       github.com/uptrace/uptrace/pkg/httputil/middleware.go:31 +0x51
net/http.serverHandler.ServeHTTP({0xc0168863f0?}, {0x3609eb0?, 0xc016138540?}, 0x6?)
       net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc0168c2000, {0x3610a20, 0xc0003320f0})
       net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 286
       net/http/server.go:3285 +0x4b4
```

Testesd on `uptrace/uptrace:1.7.2` and `uptrace/uptrace-dev:latest` containers

**Comment by vmihailenco** [comment]
Right now you should use `_count` which is an alias for `sum(_count)`. In the future we plan to replace `_count` with `sum(_count)`.

**Comment by vmihailenco** [comment]
You can now use `sum(_count)` in the master branch. I will open a new issue to support `count()` for compatibility.
