### ISSUE TITLE
not work with sentry browser sdk

### ISSUE THREAD

**Issue by newcworld** [uptrace/uptrace#377]
SentrySpan should change struct field status from uint8 to string
```
{
    "error": {
        "status": 400,
        "code": "json_unmarshal",
        "message": "json: cannot unmarshal \"\\\"ok\\\",\\\"timestamp\\\":1716363376.29,\\\"...\" into Go struct field tracing.SentryEvent[]tracing.SentrySpantracing.SentrySpan.spans.0.status of type uint8"
    },
    "statusCode": 400,
    "traceId": "17d1bf65eab538b84047a488158ce80c"
}
```

```
{
	"contexts": {
		"trace": {
			"span_id": "81debd46fe4d760f",
			"trace_id": "dc9be39d5eae4763b8791bca18551764",
			"data": {
				"sentry.origin": "auto.pageload.nextjs.pages_router_instrumentation",
				"sentry.op": "pageload",
				"sentry.source": "route",
				"sentry.sample_rate": 1,
				"effectiveConnectionType": "3g",
				"deviceMemory": "8 GB",
				"hardwareConcurrency": "11",
				"sentry.idle_span_finish_reason": "idleTimeout",
				"sentry.idle_span_discarded_spans": 5
			},
			"op": "pageload",
			"origin": "auto.pageload.nextjs.pages_router_instrumentation"
		}
	},
	"spans": [{
		"data": {
			"sentry.origin": "auto.http.browser",
			"sentry.op": "http.client",
			"url": "/_next/static/development/_devMiddlewareManifest.json",
			"type": "fetch",
			"http.method": "GET",
			"http.url": "http://localhost:3000/_next/static/development/_devMiddlewareManifest.json",
			"server.address": "localhost:3000",
			"http.response.status_code": 200,
			"network.protocol.version": "1.1",
			"network.protocol.name": "http",
			"http.request.redirect_start": 1716363374.659,
			"http.request.fetch_start": 1716363376.1501,
			"http.request.domain_lookup_start": 1716363376.1501,
			"http.request.domain_lookup_end": 1716363376.1501,
			"http.request.connect_start": 1716363376.1501,
			"http.request.secure_connection_start": 1716363374.659,
			"http.request.connection_end": 1716363376.1501,
			"http.request.request_start": 1716363376.1555,
			"http.request.response_start": 1716363376.1696,
			"http.request.response_end": 1716363376.1717
		},
		"description": "GET /_next/static/development/_devMiddlewareManifest.json",
		"op": "http.client",
		"parent_span_id": "81debd46fe4d760f",
		"span_id": "8935e4b3c008437a",
		"start_timestamp": 1716363376.1494002,
		"status": "ok",
		"timestamp": 1716363376.29,
		"trace_id": "dc9be39d5eae4763b8791bca18551764",
		"origin": "auto.http.browser"
	}, {
		"data": {
			"sentry.origin": "auto.ui.browser.metrics",
			"sentry.op": "ui.long-task"
		},
		"description": "Main UI thread blocked",
		"op": "ui.long-task",
		"parent_span_id": "81debd46fe4d760f",
		"span_id": "ac93208ca8308a4f",
		"start_timestamp": 1716363375.5326002,
		"timestamp": 1716363375.6176002,
		"trace_id": "dc9be39d5eae4763b8791bca18551764",
		"origin": "auto.ui.browser.metrics"
	}, {
		"data": {
			"sentry.origin": "auto.ui.browser.metrics",
			"sentry.op": "ui.long-task"
		},
		"description": "Main UI thread blocked",
		"op": "ui.long-task",
		"parent_span_id": "81debd46fe4d760f",
		"span_id": "b4782e782771882a",
		"start_timestamp": 1716363375.8215,
		"timestamp": 1716363375.9985,
		"trace_id": "dc9be39d5eae4763b8791bca18551764",
		"origin": "auto.ui.browser.metrics"
	}, {
		"data": {
			"sentry.origin": "auto.ui.browser.metrics",
			"sentry.op": "ui.long-task"
		},
		"description": "Main UI thread blocked",
		"op": "ui.long-task",
		"parent_span_id": "81debd46fe4d760f",
		"span_id": "88baf6c12d8a213c",
		"start_timestamp": 1716363376.0023,
		"timestamp": 1716363376.1503,
		"trace_id": "dc9be39d5eae4763b8791bca18551764",
		"origin": "auto.ui.browser.metrics"
	}, {
		"data": {
			"sentry.origin": "auto.ui.browser.metrics",
			"sentry.op": "ui.long-task"
		},
		"description": "Main UI thread blocked",
		"op": "ui.long-task",
		"parent_span_id": "81debd46fe4d760f",
		"span_id": "aaabfe1bd7945ae2",
		"start_timestamp": 1716363376.1596,
		"timestamp": 1716363376.2886,
		"trace_id": "dc9be39d5eae4763b8791bca18551764",
		"origin": "auto.ui.browser.metrics"
	}, {
		"data": {
			"sentry.origin": "auto.ui.browser.metrics",
			"sentry.op": "browser"
		},
		"description": "unloadEvent",
		"op": "browser",
		"parent_span_id": "81debd46fe4d760f",
		"span_id": "924e57bca6dd8aed",
		"start_timestamp": 1716363375.4545,
		"timestamp": 1716363375.4545,
		"trace_id": "dc9be39d5eae4763b8791bca18551764",
		"origin": "auto.ui.browser.metrics"
	}, {
		"data": {
			"sentry.origin": "auto.ui.browser.metrics",
			"sentry.op": "browser"
		},
		"description": "domContentLoadedEvent",
		"op": "browser",
		"parent_span_id": "81debd46fe4d760f",
		"span_id": "873eb1d6def432a1",
		"start_timestamp": 1716363376.1504,
		"timestamp": 1716363376.1504,
		"trace_id": "dc9be39d5eae4763b8791bca18551764",
		"origin": "auto.ui.browser.metrics"
	}, {
		"data": {
			"sentry.origin": "auto.ui.browser.metrics",
			"sentry.op": "browser"
		},
		"description": "connect",
		"op": "browser",
		"parent_span_id": "81debd46fe4d760f",
		"span_id": "b07915638fb85700",
		"start_timestamp": 1716363374.6811,
		"timestamp": 1716363374.6811,
		"trace_id": "dc9be39d5eae4763b8791bca18551764",
		"origin": "auto.ui.browser.metrics"
	}, {
		"data": {
			"sentry.origin": "auto.ui.browser.metrics",
			"sentry.op": "browser"
		},
		"description": "cache",
		"op": "browser",
		"parent_span_id": "81debd46fe4d760f",
		"span_id": "bd31519e4f00b9c5",
		"start_timestamp": 1716363374.6811,
		"timestamp": 1716363374.6811,
		"trace_id": "dc9be39d5eae4763b8791bca18551764",
		"origin": "auto.ui.browser.metrics"
	}, {
		"data": {
			"sentry.origin": "auto.ui.browser.metrics",
			"sentry.op": "browser"
		},
		"description": "DNS",
		"op": "browser",
		"parent_span_id": "81debd46fe4d760f",
		"span_id": "be8976644da7e4d6",
		"start_timestamp": 1716363374.6811,
		"timestamp": 1716363374.6811,
		"trace_id": "dc9be39d5eae4763b8791bca18551764",
		"origin": "auto.ui.browser.metrics"
	}, {
		"data": {
			"sentry.origin": "auto.ui.browser.metrics",
			"sentry.op": "browser"
		},
		"description": "request",
		"op": "browser",
		"parent_span_id": "81debd46fe4d760f",
		"span_id": "bd7725b5b4ff9d97",
		"start_timestamp": 1716363374.7612998,
		"timestamp": 1716363375.4450998,
		"trace_id": "dc9be39d5eae4763b8791bca18551764",
		"origin": "auto.ui.browser.metrics"
	}, {
		"data": {
			"sentry.origin": "auto.ui.browser.metrics",
			"sentry.op": "browser"
		},
		"description": "response",
		"op": "browser",
		"parent_span_id": "81debd46fe4d760f",
		"span_id": "b65835dd0ef212d1",
		"start_timestamp": 1716363375.4427,
		"timestamp": 1716363375.4450998,
		"trace_id": "dc9be39d5eae4763b8791bca18551764",
		"origin": "auto.ui.browser.metrics"
	}, {
		"data": {
			"sentry.origin": "auto.resource.browser.metrics",
			"sentry.op": "measure"
		},
		"description": "Next.js-before-hydration",
		"op": "measure",
		"parent_span_id": "81debd46fe4d760f",
		"span_id": "83177d49dad7e2ab",
		"start_timestamp": 1716363374.659,
		"timestamp": 1716363376.2926,
		"trace_id": "dc9be39d5eae4763b8791bca18551764",
		"origin": "auto.resource.browser.metrics"
	}, {
		"data": {
			"sentry.origin": "auto.resource.browser.metrics",
			"sentry.op": "resource.script",
			"http.response_transfer_size": 9438,
			"http.response_content_length": 9138,
			"http.decoded_response_content_length": 47935,
			"resource.render_blocking_status": "non-blocking",
			"url.scheme": "http",
			"server.address": "localhost:3000",
			"url.same_origin": true
		},
		"description": "/_next/static/chunks/webpack.js?ts=1716363375425",
		"op": "resource.script",
		"parent_span_id": "81debd46fe4d760f",
		"span_id": "b4d92f0b2b584e00",
		"start_timestamp": 1716363375.4726999,
		"timestamp": 1716363375.5170999,
		"trace_id": "dc9be39d5eae4763b8791bca18551764",
		"origin": "auto.resource.browser.metrics"
	}, {
		"data": {
			"sentry.origin": "auto.resource.browser.metrics",
			"sentry.op": "resource.script",
			"http.response_transfer_size": 1165934,
			"http.response_content_length": 1165634,
			"http.decoded_response_content_length": 4876189,
			"resource.render_blocking_status": "non-blocking",
			"url.scheme": "http",
			"server.address": "localhost:3000",
			"url.same_origin": true
		},
		"description": "/_next/static/chunks/main.js?ts=1716363375425",
		"op": "resource.script",
		"parent_span_id": "81debd46fe4d760f",
		"span_id": "880166761f09906b",
		"start_timestamp": 1716363375.4728,
		"timestamp": 1716363375.7624,
		"trace_id": "dc9be39d5eae4763b8791bca18551764",
		"origin": "auto.resource.browser.metrics"
	}, {
		"data": {
			"sentry.origin": "auto.resource.browser.metrics",
			"sentry.op": "resource.script",
			"http.response_transfer_size": 1033096,
			"http.response_content_length": 1032796,
			"http.decoded_response_content_length": 3972944,
			"resource.render_blocking_status": "non-blocking",
			"url.scheme": "http",
			"server.address": "localhost:3000",
			"url.same_origin": true
		},
		"description": "/_next/static/chunks/pages/_app.js?ts=1716363375425",
		"op": "resource.script",
		"parent_span_id": "81debd46fe4d760f",
		"span_id": "a301239fbe3d1d46",
		"start_timestamp": 1716363375.4729,
		"timestamp": 1716363375.8983998,
		"trace_id": "dc9be39d5eae4763b8791bca18551764",
		"origin": "auto.resource.browser.metrics"
	}, {
		"data": {
			"sentry.origin": "auto.resource.browser.metrics",
			"sentry.op": "resource.script",
			"http.response_transfer_size": 24879,
			"http.response_content_length": 24579,
			"http.decoded_response_content_length": 77191,
			"resource.render_blocking_status": "non-blocking",
			"url.scheme": "http",
			"server.address": "localhost:3000",
			"url.same_origin": true
		},
		"description": "/_next/static/chunks/react-refresh.js?ts=1716363375425",
		"op": "resource.script",
		"parent_span_id": "81debd46fe4d760f",
		"span_id": "a1a244886659b347",
		"start_timestamp": 1716363375.4729998,
		"timestamp": 1716363375.5266,
		"trace_id": "dc9be39d5eae4763b8791bca18551764",
		"origin": "auto.resource.browser.metrics"
	}, {
		"data": {
			"sentry.origin": "auto.resource.browser.metrics",
			"sentry.op": "resource.script",
			"http.response_transfer_size": 596,
			"http.response_content_length": 296,
			"http.decoded_response_content_length": 296,
			"resource.render_blocking_status": "non-blocking",
			"url.scheme": "http",
			"server.address": "localhost:3000",
			"url.same_origin": true
		},
		"description": "/_next/static/development/_buildManifest.js?ts=1716363375425",
		"op": "resource.script",
		"parent_span_id": "81debd46fe4d760f",
		"span_id": "9b67f7db22b558d6",
		"start_timestamp": 1716363375.4729998,
		"timestamp": 1716363375.6862,
		"trace_id": "dc9be39d5eae4763b8791bca18551764",
		"origin": "auto.resource.browser.metrics"
	}, {
		"data": {
			"sentry.origin": "auto.resource.browser.metrics",
			"sentry.op": "resource.script",
			"http.response_transfer_size": 376,
			"http.response_content_length": 76,
			"http.decoded_response_content_length": 76,
			"resource.render_blocking_status": "non-blocking",
			"url.scheme": "http",
			"server.address": "localhost:3000",
			"url.same_origin": true
		},
		"description": "/_next/static/development/_ssgManifest.js?ts=1716363375425",
		"op": "resource.script",
		"parent_span_id": "81debd46fe4d760f",
		"span_id": "903f22d7f265453e",
		"start_timestamp": 1716363375.4729998,
		"timestamp": 1716363375.6907997,
		"trace_id": "dc9be39d5eae4763b8791bca18551764",
		"origin": "auto.resource.browser.metrics"
	}, {
		"data": {
			"sentry.origin": "auto.resource.browser.metrics",
			"sentry.op": "resource.script",
			"http.response_transfer_size": 159977,
			"http.response_content_length": 159677,
			"http.decoded_response_content_length": 527673,
			"resource.render_blocking_status": "non-blocking",
			"url.scheme": "http",
			"server.address": "localhost:3000",
			"url.same_origin": true
		},
		"description": "/_next/static/chunks/pages/index.js?ts=1716363375425",
		"op": "resource.script",
		"parent_span_id": "81debd46fe4d760f",
		"span_id": "ba3e96b94833c7fc",
		"start_timestamp": 1716363375.4729998,
		"timestamp": 1716363375.7315998,
		"trace_id": "dc9be39d5eae4763b8791bca18551764",
		"origin": "auto.resource.browser.metrics"
	}, {
		"data": {
			"sentry.origin": "auto.resource.browser.metrics",
			"sentry.op": "mark"
		},
		"description": "sentry-tracing-init",
		"op": "mark",
		"parent_span_id": "81debd46fe4d760f",
		"span_id": "89cb720a98ced65e",
		"start_timestamp": 1716363376.1172,
		"timestamp": 1716363376.1172,
		"trace_id": "dc9be39d5eae4763b8791bca18551764",
		"origin": "auto.resource.browser.metrics"
	}],
	"start_timestamp": 1716363374.659,
	"timestamp": 1716363376.29,
	"transaction": "/",
	"type": "transaction",
	"transaction_info": {
		"source": "route"
	},
	"measurements": {
		"ttfb": {
			"value": 783.7000000178814,
			"unit": "millisecond"
		},
		"fp": {
			"value": 1674.800000011921,
			"unit": "millisecond"
		},
		"fcp": {
			"value": 1674.800000011921,
			"unit": "millisecond"
		},
		"connection.rtt": {
			"value": 400,
			"unit": "millisecond"
		},
		"ttfb.requestTime": {
			"value": 681.4000000059605,
			"unit": "millisecond"
		}
	},
	"platform": "javascript",
	"request": {
		"url": "http://localhost:3000/",
		"headers": {
			"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
		}
	},
	"event_id": "56a0332accd147169e535508b7876f98",
	"environment": "development",
	"sdk": {
		"integrations": ["InboundFilters", "FunctionToString", "BrowserApiErrors", "Breadcrumbs", "GlobalHandlers", "LinkedErrors", "Dedupe", "HttpContext", "BrowserTracing", "NextjsClientStackFrameNormalization"],
		"name": "sentry.javascript.nextjs",
		"version": "8.2.1",
		"packages": [{
			"name": "npm:@sentry/nextjs",
			"version": "8.2.1"
		}, {
			"name": "npm:@sentry/react",
			"version": "8.2.1"
		}]
	},
	"tags": {
		"runtime": "browser"
	},
	"breadcrumbs": [{
		"timestamp": 1716363376.13,
		"category": "sentry.event",
		"event_id": "5082ce23464c4492881783ae4e096367",
		"level": "info",
		"message": "Hello, world!"
	}, {
		"timestamp": 1716363376.289,
		"category": "fetch",
		"data": {
			"method": "GET",
			"url": "/_next/static/development/_devMiddlewareManifest.json",
			"__span": "8935e4b3c008437a",
			"status_code": 200
		},
		"type": "http"
	}, {
		"timestamp": 1716363376.291,
		"category": "navigation",
		"data": {
			"from": "/",
			"to": "/"
		}
	}]
}
```

**Comment by newcworld** [comment]
also, get panic
```
panic: assignment to entry in nil map [recovered]
	panic: assignment to entry in nil map

goroutine 1224 [running]:
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.deferwrap1()
	go.opentelemetry.io/otel/sdk@v1.23.1/trace/span.go:405 +0x25
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc00da0a000, {0x0, 0x0, 0xc0005bf340?})
	go.opentelemetry.io/otel/sdk@v1.23.1/trace/span.go:443 +0xa82
panic({0x17c6cc0?, 0x35f3f00?})
	runtime/panic.go:770 +0x132
github.com/uptrace/uptrace/pkg/tracing.initEventFromHostSpan(0xc0004e9680, 0x360dd20?, 0xc009ba1540)
	github.com/uptrace/uptrace/pkg/tracing/span_attrs.go:469 +0x20e
github.com/uptrace/uptrace/pkg/tracing.(*spanProcessorThread)._processSpans(0xc007ef5f68, {0x360dd20, 0xc00a70e6f0}, {0xc0089aea08, 0x33d, 0x33d?})
	github.com/uptrace/uptrace/pkg/tracing/span_processor.go:195 +0x114d
github.com/uptrace/uptrace/pkg/tracing.(*SpanProcessor).processSpans.func1()
	github.com/uptrace/uptrace/pkg/tracing/span_processor.go:153 +0x1db
created by github.com/uptrace/uptrace/pkg/tracing.(*SpanProcessor).processSpans in goroutine 73
	github.com/uptrace/uptrace/pkg/tracing/span_processor.go:147 +0x165
```

**Comment by spirkaa** [comment]
Same with python (sentry-sdk==1.45.0)

```log
[bunrouter]  11:48:00.838  17d30774b7b711b7671f972d2234b2b1   400      1.411ms   POST     /api/2/envelope/       *json.UnmarshalTypeError: json: cannot unmarshal "false,\"redis.command\":\"GET\",\"db...." into Go struct field tracing.SentryEvent[]tracing.SentrySpantracing.SentrySpanmap[string]string.spans.19.tags.redis.is_cluster of type string

2024-05-26T11:49:00.860Z       error   tracing/sentry_handler.go:360   sentry: unsupported item type   {"type": "sessions"}
github.com/uptrace/uptrace/pkg/tracing.(*SentryHandler).Envelope
       github.com/uptrace/uptrace/pkg/tracing/sentry_handler.go:360
github.com/uptrace/bunrouter/extra/bunrouterotel.(*config).Middleware-fm.(*config).Middleware.func1
       github.com/uptrace/bunrouter/extra/bunrouterotel@v1.0.21/bunrouterotel.go:70
github.com/uptrace/uptrace/pkg/bunapp.(*App).httpErrorHandler-fm.(*App).httpErrorHandler.func1
       github.com/uptrace/uptrace/pkg/bunapp/app.go:231
github.com/uptrace/bunrouter/extra/reqlog.(*middleware).Middleware-fm.(*middleware).Middleware.func1
       github.com/uptrace/bunrouter/extra/reqlog@v1.0.21/middleware.go:77
github.com/uptrace/bunrouter.(*Router).ServeHTTPError
       github.com/uptrace/bunrouter@v1.0.21/router.go:52
github.com/uptrace/bunrouter.(*Router).ServeHTTP
       github.com/uptrace/bunrouter@v1.0.21/router.go:45
github.com/klauspost/compress/gzhttp.NewWrapper.func1.1
       github.com/klauspost/compress@v1.17.6/gzhttp/compress.go:501
net/http.HandlerFunc.ServeHTTP
       net/http/server.go:2166
github.com/uptrace/uptrace/pkg/httputil.DecompressHandler.ServeHTTP
       github.com/uptrace/uptrace/pkg/httputil/middleware.go:53
github.com/uptrace/uptrace/pkg/httputil.(*TraceparentHandler).ServeHTTP
       github.com/uptrace/uptrace/pkg/httputil/middleware.go:90
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP
       go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.48.0/handler.go:225
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1
       go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.48.0/handler.go:83
net/http.HandlerFunc.ServeHTTP
       net/http/server.go:2166
main.init.func2.(*Cors).Handler.11
       github.com/rs/cors@v1.10.1/cors.go:281
net/http.HandlerFunc.ServeHTTP
       net/http/server.go:2166
github.com/uptrace/uptrace/pkg/httputil.PanicHandler.ServeHTTP
       github.com/uptrace/uptrace/pkg/httputil/middleware.go:31
net/http.serverHandler.ServeHTTP
       net/http/server.go:3137
net/http.(*conn).serve
       net/http/server.go:2039
```

**Comment by newcworld** [comment]
I think maybe uptrace can integrated sentry-go.
No need to maintain your own defined structure

@vmihailenco 

https://github.com/getsentry/sentry-go/blob/master/interfaces.go

**Comment by vmihailenco** [comment]
@newcworld that would work for the data generated by sentry-go. Other Sentry clients send data in slightly different formats.

I think most of this should be fixed by https://github.com/uptrace/uptrace/commit/4cb66b8c10a6a77b7ef98df92c158b0dc8f4c33a
