### ISSUE TITLE
Uptrace crashes on saving the edited WebHook Notification channel

### ISSUE THREAD

**Issue by amedveshchek** [uptrace/uptrace#383]
Configuration:
- Uptrace self-hosted in docker
- Also tested in the cloud, it has issues as well (see below)
- Tested on OS: Ubuntu, Mac

Steps to reproduce:
- Create a Webhook Notifcation channel (name: `Test`, url: `https://example.com` or any other URL)
- Open this channel to edit, and change the Webhook URL
- Click "Save" button
  - in self-hosted version: `uptrace` service crashes (stack trace is below) - and since the UI is retrying, it goes into an infinite loop of restarts until we navigate to another page
  - in the cloud, shows the red error "404 Not found" on top of the page, but in the network insepction we can see `HTTP 400` with some details

Stack trace from the logs:
```
panic: runtime error: invalid memory address or nil pointer dereference
goroutine 240 [running]:
github.com/uptrace/uptrace/pkg/httputil.PanicHandler.ServeHTTP.func1()
	github.com/uptrace/uptrace/pkg/httputil/middleware.go:25 +0x5b
panic({0x17c8a60?, 0x42dc900?})
	runtime/panic.go:770 +0x132
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.deferwrap1()
	go.opentelemetry.io/otel/sdk@v1.23.1/trace/span.go:405 +0x25
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc0015fc000, {0x0, 0x0, 0xc00099c5a0?})
	go.opentelemetry.io/otel/sdk@v1.23.1/trace/span.go:443 +0xa82
panic({0x17c8a60?, 0x42dc900?})
	runtime/panic.go:770 +0x132
github.com/uptrace/uptrace/pkg/alerting.NewWebhookMessage(0xc0006e10e0, {0x3613b20?, 0xc0014b4c80?}, {0x0, 0x0})
	github.com/uptrace/uptrace/pkg/alerting/notif_channel_handler.go:565 +0x57
github.com/uptrace/uptrace/pkg/alerting.notifyByWebhookChannel({0x3610a20, 0xc001619470}, 0xc0006e10e0, 0x1785540?, {0x3613b20?, 0xc0014b4c80?}, 0xc001619290)
	github.com/uptrace/uptrace/pkg/alerting/notif_webhook.go:58 +0x185
github.com/uptrace/uptrace/pkg/alerting.(*NotifChannelHandler).sendWebhookTestMsg(0xc001503a70, {0x3610a20, 0xc001619470}, 0xc001641830, 0xc001619290)
	github.com/uptrace/uptrace/pkg/alerting/notif_channel_handler.go:476 +0x206
github.com/uptrace/uptrace/pkg/alerting.(*NotifChannelHandler).WebhookUpdate(0xc001503a70, {0x360d250, 0xc0014f6f50}, {0xc0015f65a0, {{0xc000043774, 0x37}, 0xc001511f00, 0xc00152a140, 0x0}})
	github.com/uptrace/uptrace/pkg/alerting/notif_channel_handler.go:442 +0x232
github.com/uptrace/uptrace/pkg/alerting.(*Middleware).NotifChannel-fm.(*Middleware).NotifChannel.func1({0x360d250, 0xc0014f6f50}, {0xc0015f6360, {{0xc000043774, 0x37}, 0xc001511f00, 0xc00152a140, 0x0}})
	github.com/uptrace/uptrace/pkg/alerting/init.go:210 +0x31d
github.com/uptrace/uptrace/pkg/org.(*Middleware).UserAndProject-fm.(*Middleware).UserAndProject.func1({0x360d250, 0xc0014f6f50}, {0xc0015f6120, {{0xc000043774, 0x37}, 0xc001511f00, 0xc00152a140, 0x0}})
	github.com/uptrace/uptrace/pkg/org/auth.go:105 +0x24f
github.com/uptrace/bunrouter/extra/bunrouterotel.(*config).Middleware-fm.(*config).Middleware.func1({0x360d250, 0xc0014f6f50}, {0xc0015f6120, {{0xc000043774, 0x37}, 0xc001511f00, 0xc00152a140, 0x0}})
	github.com/uptrace/bunrouter/extra/bunrouterotel@v1.0.21/bunrouterotel.go:70 +0xa99
github.com/uptrace/uptrace/pkg/bunapp.(*App).httpErrorHandler-fm.(*App).httpErrorHandler.func1({0x360d250, 0xc0014f6f50}, {0xc0015f6120, {{0xc000043774, 0x37}, 0xc001511f00, 0xc00152a140, 0x0}})
	github.com/uptrace/uptrace/pkg/bunapp/app.go:231 +0x90
github.com/uptrace/bunrouter/extra/reqlog.(*middleware).Middleware-fm.(*middleware).Middleware.func1({0x3609fa0?, 0xc00099c5a0?}, {0xc0015f6120, {{0xc000043774, 0x37}, 0xc001511f00, 0xc00152a140, 0x0}})
	github.com/uptrace/bunrouter/extra/reqlog@v1.0.21/middleware.go:77 +0x124
github.com/uptrace/bunrouter.(*Router).ServeHTTPError(0x793201?, {0x3609fa0, 0xc00099c5a0}, 0xc0015f6120)
	github.com/uptrace/bunrouter@v1.0.21/router.go:52 +0x108
github.com/uptrace/bunrouter.(*Router).ServeHTTP(0x42e1f60?, {0x3609fa0?, 0xc00099c5a0?}, 0x4?)
	github.com/uptrace/bunrouter@v1.0.21/router.go:45 +0x1d
github.com/klauspost/compress/gzhttp.NewWrapper.func1.1({0x360d2b0, 0xc00147bb00}, 0xc0015f6120)
	github.com/klauspost/compress@v1.17.6/gzhttp/compress.go:495 +0x54f
net/http.HandlerFunc.ServeHTTP(0xc0015f6120?, {0x360d2b0?, 0xc00147bb00?}, 0x3610a20?)
	net/http/server.go:2166 +0x29
github.com/uptrace/uptrace/pkg/httputil.DecompressHandler.ServeHTTP({{0x35fcee0?, 0xc00047e520?}}, {0x360d2b0, 0xc00147bb00}, 0xc0015f6120)
	github.com/uptrace/uptrace/pkg/httputil/middleware.go:53 +0x1a3
github.com/uptrace/uptrace/pkg/httputil.(*TraceparentHandler).ServeHTTP(0xc00047e540, {0x360d2b0, 0xc00147bb00}, 0xc0015f6120)
	github.com/uptrace/uptrace/pkg/httputil/middleware.go:90 +0xb4
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP(0xc001951930, {0x3609eb0, 0xc001526540}, 0xc0015f6000, {0x35fcf20, 0xc00047e540})
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.48.0/handler.go:225 +0x1243
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1({0x3609eb0?, 0xc001526540?}, 0x1?)
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.48.0/handler.go:83 +0x35
net/http.HandlerFunc.ServeHTTP(0xc0015260e0?, {0x3609eb0?, 0xc001526540?}, 0xc0015f6000?)
	net/http/server.go:2166 +0x29
main.init.func2.(*Cors).Handler.11({0x3609eb0, 0xc001526540}, 0xc0015f6000)
	github.com/rs/cors@v1.10.1/cors.go:281 +0x184
net/http.HandlerFunc.ServeHTTP(0xc001618db0?, {0x3609eb0?, 0xc001526540?}, 0x0?)
	net/http/server.go:2166 +0x29
github.com/uptrace/uptrace/pkg/httputil.PanicHandler.ServeHTTP({{0x35fcee0?, 0xc00047e700?}}, {0x3609eb0?, 0xc001526540?}, 0x0?)
	github.com/uptrace/uptrace/pkg/httputil/middleware.go:31 +0x51
net/http.serverHandler.ServeHTTP({0x36052b0?}, {0x3609eb0?, 0xc001526540?}, 0x6?)
	net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc0000a5710, {0x3610a20, 0xc0015014d0})
	net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 230
	net/http/server.go:3285 +0x4b4
```

**Comment by vmihailenco** [comment]
I believe this was fixed some time ago. Thanks for reporting.
