### ISSUE TITLE
Error saving spans data

### ISSUE THREAD

**Issue by arend-melissant-tnt** [uptrace/uptrace#439]
Using .net to send spans i get the following error, after which uptarce crashes. 
I am on 1.7.7

error is: failed: createMatView failed: DB::Exception: Column s.count is not under aggregate function

**Comment by arend-melissant-tnt** [comment]
2024-11-26T09:55:41.914Z    info    metrics/datapoint_processor.go:66    starting processing metrics...    {"threads": 4, "batch_size": 4000, "buffer_size": 16000, "cum_to_delta_size": 40000}                                          ││ [ch]  09:55:41.997   CREATE VIEW           4.506ms  CREATE MATERIALIZED VIEW "metrics_uptrace_tracing_logs_mv" TO uptrace.datapoint_minutes AS SELECT s.project_id, 'uptrace_tracing_logs' AS metric, toStartOfMinute(s.time) AS time, ' ││ counter' AS instrument, xxHash64(arrayStringConcat([toString(s."service_name"), toString(s."host_name"), toString(s."log_severity")], '-')) AS attrs_hash, ['service_name', 'host_name', 'log_severity'] AS string_keys, [toString(s."se ││ rvice_name"), toString(s."host_name"), toString(s."log_severity")] AS string_values, toJSONString(map('log_message', toString(any(s.string_values[indexOf(s.string_keys, 'log_message')])))) AS annotations, s."count" AS sum FROM uptra ││ ce.spans_index AS s GROUP BY s.project_id, toStartOfMinute(s.time), toString(s."service_name"), toString(s."host_name"), toString(s."log_severity") SETTINGS allow_experimental_analyzer = 1       *ch.Error: DB::Exception: Column s.co ││ unt is not under aggregate function and not in GROUP BY keys. In query SELECT s.project_id, 'uptrace_tracing_logs' AS metric, toStartOfMinute(s.time) AS time, 'counter' AS instrument, xxHash64(arrayStringConcat([toString(s.service_n ││ ame), toString(s.host_name), toString(s.log_severity)], '-')) AS attrs_hash, ['service_name', 'host_name', 'log_severity'] AS string_keys, [toString(s.service_name), toString(s.host_name), toString(s.log_severity)] AS string_values, ││  toJSONString(map('log_message', toString(any(s.string_values[indexOf(s.string_keys, 'log_message')])))) AS annotations, s.count AS sum FROM uptrace.spans_index AS s GROUP BY s.project_id, toStartOfMinute(s.time), toString(s.service ││ _name), toString(s.host_name), toString(s.log_severity) SETTINGS allow_experimental_analyzer = 1 (215)                                                                                                                                   ││ 2024-11-26T09:55:41.998Z    error    metrics/init.go:43    initSpanMetrics failed    {"error": "createSpanMetric \"uptrace_tracing_logs\" failed: createMatView failed: DB::Exception: Column s.count is not under aggregate function an ││ d not in GROUP BY keys. In query SELECT s.project_id, 'uptrace_tracing_logs' AS metric, toStartOfMinute(s.time) AS time, 'counter' AS instrument, xxHash64(arrayStringConcat([toString(s.service_name), toString(s.host_name), toString( ││ s.log_severity)], '-')) AS attrs_hash, ['service_name', 'host_name', 'log_severity'] AS string_keys, [toString(s.service_name), toString(s.host_name), toString(s.log_severity)] AS string_values, toJSONString(map('log_message', toStr ││ ing(any(s.string_values[indexOf(s.string_keys, 'log_message')])))) AS annotations, s.count AS sum FROM uptrace.spans_index AS s GROUP BY s.project_id, toStartOfMinute(s.time), toString(s.service_name), toString(s.host_name), toStrin ││ g(s.log_severity) SETTINGS allow_experimental_analyzer = 1 (215)"}

**Comment by arend-melissant-tnt** [comment]
uptrace crashes with following error, mayve unrelated to the view error above????

ch: 2024/11/26 13:00:26 pool.go:284: Conn has unread data                                                                                                                                                                                ││ panic: runtime error: invalid memory address or nil pointer dereference                                                                                                                                                                  ││                                                                                                                                                                                                                                          │
│ goroutine 100151 [running]:                                                                                                                                                                                                              │
│ github.com/uptrace/uptrace/pkg/httputil.PanicHandler.ServeHTTP.func1()                                                                                                                                                                   ││     github.com/uptrace/uptrace/pkg/httputil/middleware.go:25 +0x5b                                                                                                                                                                       ││ panic({0x17eae00?, 0x431ba70?})                                                                                                                                                                                                          ││     runtime/panic.go:770 +0x132                                                                                                                                                                                                          ││ go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.deferwrap1()                                                                                                                                                                     ││     go.opentelemetry.io/otel/sdk@v1.28.0/trace/span.go:398 +0x25                                                                                                                                                                         ││ go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc0024816c0, {0x0, 0x0, 0xc003a3efc0?})                                                                                                                                         ││     go.opentelemetry.io/otel/sdk@v1.28.0/trace/span.go:436 +0xa82                                                                                                                                                                        ││ panic({0x17eae00?, 0x431ba70?})                                                                                                                                                                                                          ││     runtime/panic.go:770 +0x132                                                                                                                                                                                                          ││ github.com/uptrace/uptrace/pkg/tracing.(*otlpLogProcessor).processLogRecord(0xc0007a67c0, 0xc0007a6790, 0xc0029c8580)                                                                                                                    │
│     github.com/uptrace/uptrace/pkg/tracing/otlp_logs.go:208 +0x488                                                                                                                                                                       ││ github.com/uptrace/uptrace/pkg/tracing.(*LogsServiceServer).export(0xc00004c1a0, {0x3639a98, 0xc00813ae10}, {0xc001ffef80, 0x1, 0xc006c60000?}, 0xc0029d8000)                                                                            ││     github.com/uptrace/uptrace/pkg/tracing/otlp_logs.go:168 +0x45b                                                                                                                                                                       ││ github.com/uptrace/uptrace/pkg/tracing.(*LogsServiceServer).ExportHTTP(0xc00004c1a0, {0x3635f40, 0xc0029cb9c0}, {0xc0038f85a0, {{0xc007580e2d, 0x8}, 0xc000502180, 0xc00004c3e0, 0x0}})                                                  ││     github.com/uptrace/uptrace/pkg/tracing/otlp_logs.go:100 +0x31f                                                                                                                                                                       ││ github.com/uptrace/bunrouter/extra/bunrouterotel.(*config).Middleware-fm.(*config).Middleware.func1({0x3635f40, 0xc0029cb9c0}, {0xc0038f85a0, {{0xc007580e2d, 0x8}, 0xc000502180, 0xc00004c3e0, 0x0}})                                   ││     github.com/uptrace/bunrouter/extra/bunrouterotel@v1.0.21/bunrouterotel.go:70 +0xa99                                                                                                                                                  ││ github.com/uptrace/uptrace/pkg/bunapp.(*App).httpErrorHandler-fm.(*App).httpErrorHandler.func1({0x3635f40, 0xc0029cb9c0}, {0xc0038f85a0, {{0xc007580e2d, 0x8}, 0xc000502180, 0xc00004c3e0, 0x0}})                                        ││     github.com/uptrace/uptrace/pkg/bunapp/app.go:231 +0x90                                                                                                                                                                               ││ github.com/uptrace/bunrouter/extra/reqlog.(*middleware).Middleware-fm.(*middleware).Middleware.func1({0x3632f78?, 0xc0029cb980?}, {0xc0038f85a0, {{0xc007580e2d, 0x8}, 0xc000502180, 0xc00004c3e0, 0x0}})                                ││     github.com/uptrace/bunrouter/extra/reqlog@v1.0.21/middleware.go:77 +0x124                                                                                                                                                            ││ github.com/uptrace/bunrouter.(*Router).ServeHTTPError(0x40?, {0x3632f78, 0xc0029cb980}, 0xc0038f85a0)                                                                                                                                    ││     github.com/uptrace/bunrouter@v1.0.21/router.go:52 +0x108                                                                                                                                                                             ││ github.com/uptrace/bunrouter.(*Router).ServeHTTP(0x196fda0?, {0x3632f78?, 0xc0029cb980?}, 0x4?)                                                                                                                                          ││     github.com/uptrace/bunrouter@v1.0.21/router.go:45 +0x1d                                                                                                                                                                              ││ github.com/klauspost/compress/gzhttp.NewWrapper.func1.1({0x3636120, 0xc0070413e0}, 0xc0038f85a0)                                                                                                                                         ││     github.com/klauspost/compress@v1.17.6/gzhttp/compress.go:501 +0x453                                                                                                                                                                  ││ net/http.HandlerFunc.ServeHTTP(0xc0038f85a0?, {0x3636120?, 0xc0070413e0?}, 0x3639a98?)                                                                                                                                                   ││     net/http/server.go:2171 +0x29                                                                                                                                                                                                        ││ github.com/uptrace/uptrace/pkg/httputil.DecompressHandler.ServeHTTP({{0x3625c20?, 0xc0006f2900?}}, {0x3636120, 0xc0070413e0}, 0xc0038f85a0)                                                                                              ││     github.com/uptrace/uptrace/pkg/httputil/middleware.go:53 +0x1a3                                                                                                                                                                      ││ github.com/uptrace/uptrace/pkg/httputil.(*TraceparentHandler).ServeHTTP(0xc0006f2920, {0x3636120, 0xc0070413e0}, 0xc0038f85a0)                                                                                                           ││     github.com/uptrace/uptrace/pkg/httputil/middleware.go:90 +0xb4                                                                                                                                                                       ││ go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP(0xc0005e2410, {0x3632eb8, 0xc002ac17a0}, 0xc0038f8480, {0x3625c60, 0xc0006f2920})                                                                  ││     go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.48.0/handler.go:225 +0x1243                                                                                                                                         ││ go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1({0x3632eb8?, 0xc002ac17a0?}, 0x1?)                                                                                                                   ││     go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.48.0/handler.go:83 +0x35                                                                                                                                            ││ net/http.HandlerFunc.ServeHTTP(0xc00226a380?, {0x3632eb8?, 0xc002ac17a0?}, 0xc0038f8480?)                                                                                                                                                ││     net/http/server.go:2171 +0x29                                                                                                                                                                                                        ││ main.init.func2.(*Cors).Handler.11({0x3632eb8, 0xc002ac17a0}, 0xc0038f8480)                                                                                                                                                              ││     github.com/rs/cors@v1.10.1/cors.go:281 +0x184                                                                                                                                                                                        ││ net/http.HandlerFunc.ServeHTTP(0xc00813acf0?, {0x3632eb8?, 0xc002ac17a0?}, 0x0?)                                                                                                                                                         ││     net/http/server.go:2171 +0x29                                                                                                                                                                                                        ││ github.com/uptrace/uptrace/pkg/httputil.PanicHandler.ServeHTTP({{0x3625c20?, 0xc0006f2b80?}}, {0x3632eb8?, 0xc002ac17a0?}, 0x0?)                                                                                                         ││     github.com/uptrace/uptrace/pkg/httputil/middleware.go:31 +0x51                                                                                                                                                                       ││ net/http.serverHandler.ServeHTTP({0x362e050?}, {0x3632eb8?, 0xc002ac17a0?}, 0x6?)                                                                                                                                                        ││     net/http/server.go:3142 +0x8e                                                                                                                                                                                                        ││ net/http.(*conn).serve(0xc006cfe5a0, {0x3639a98, 0xc0033321e0})                                                                                                                                                                          ││     net/http/server.go:2044 +0x5e8                                                                                                                                                                                                       ││ created by net/http.(*Server).Serve in goroutine 378                                                                                                                                                                                     ││     net/http/server.go:3290 +0x4b4
